### ISSUE TITLE
Deployment with Elastic Beanstalk

### ISSUE THREAD

**Issue by santosh** [santosh/eldiario#10]
Beanstalk method implementation is experimental. It is just for demonstration purpose.

EC2 instances always running will cost unwanted charges. There will be a manual docker based deployment otherwise.

**Comment by santosh** [comment]
Note that the deployment goes through Travis and none of the AWS services. To deploy this app to Beanstalk. 

- Create an application from [AWS console](https://console.aws.amazon.com/elasticbeanstalk/home). This will also create an S3 Bucket. S3 is where code is uploaded before deployment.
- Get the access and secret key from the IAM Console. 
- Stick this to the .travis.yml

```yaml
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: "ap-south-1"
  app: "yourApp"
  env: "yourApp-env"
  bucket_name: $AWS_BUCKET_NAME
```

Pass those environment variables from Travis console.
